-- Zona Audio ? cat?logo inicial
-- Ejecuta despu?s de supabase/schema.sql.

insert into public.products (
  name, brand, category, subcategory, price, original_price, rating,
  review_count, stock, is_new, is_featured, is_best_seller, is_top_deal,
  has_audio_preview, free_shipping, image_fit, images, description, specs,
  features, sound_demo, is_published
) values
  (
    'Piano Yamaha PSR-E383',
    'Yamaha',
    'Teclados y pianos',
    'Teclados portátiles',
    370,
    null,
    4.88,
    62,
    6,
    true,
    true,
    false,
    false,
    false,
    false,
    'contain',
    ARRAY['/products/yamaha-psr-e383-1.jpg', '/products/yamaha-psr-e383-2.jpg', '/products/yamaha-psr-e383-3.jpg']::text[],
    'El Yamaha PSR-E383 es un teclado portátil de 61 teclas diseñado principalmente para estudiantes y músicos de nivel principiante o intermedio que buscan dinamismo y versatilidad a un costo accesible.',
    '{"Nombre del teclado":"Yamaha PSR-E383","Generador de sonido":"Muestreo estéreo AWM (Advanced Wave Memory)","Tonos / Voces":"650 tonos en total (incluye 258 voces de panel, 25 kits de batería/SFX, 20 arpegios, 347 voces XGlite y 12 voces Super Articulation Lite)","Pantalla":"Pantalla LCD retroiluminada en color azul","Interfaz de audio":"Interfaz integrada vía puerto USB TO HOST (transmite tanto datos MIDI como audio digital estéreo a 44.1 kHz / 16-bit hacia una computadora o dispositivo móvil)","Peso":"4.4 kg"}'::jsonb,
    ARRAY['Teclado portátil de 61 teclas', '650 tonos, 25 kits de batería y 20 arpegios', 'Pantalla LCD retroiluminada en color azul', 'Conexión USB TO HOST para MIDI y audio estéreo']::text[],
    '{"type":"synth_pad","duration":5,"notesDescription":"Yamaha PSR-E383 de 61 teclas"}'::jsonb,
    true
  ),
  (
    'Micrófonos inalámbricos Shure SN-808',
    'Shure',
    'Audio profesional y micrófonos',
    'Sistemas inalámbricos',
    105,
    null,
    4.96,
    312,
    14,
    true,
    true,
    true,
    false,
    false,
    true,
    'contain',
    ARRAY['/products/shure-sn-808-1.jpg', '/products/shure-sn-808-2.jpg']::text[],
    'El micrófono Shure SN-808 es un sistema de micrófonos inalámbricos de 4 canales diseñado para eventos en vivo, conferencias, iglesias y agrupaciones que requieren capturar múltiples voces en simultáneo.',
    '{"Tipo de micrófono":"Dinámico unidireccional (patrón polar cardioide).","Respuesta de frecuencia":"50 Hz – 15 kHz.","Preamplificador integrado":"No incluye preamplificador de audio interno en los micrófonos; la ganancia se controla directamente desde la consola, amplificador o mezclador al que se conecta el receptor.","Requisitos de alimentación":"Micrófonos: Batería de litio recargable 18650 de 3.7V (2000 mAh) por micrófono.\nReceptor: Adaptador de corriente externa DC 12V / 1A (incluido).","Conectores (Receptor)":"4 salidas balanceadas XLR (una salida independiente por cada canal).\n1 salida no balanceada Jack 6.35 mm (Plug 1/4\") Mix Out (mezcla general de los 4 canales)."}'::jsonb,
    ARRAY['Sistema inalámbrico de 4 canales', 'Set de 4 micrófonos inalámbricos', 'Cuatro salidas balanceadas XLR', 'Micrófonos con batería recargable de litio']::text[],
    '{"type":"mic_warmth","duration":5,"notesDescription":"Micrófonos inalámbricos Shure SN-808"}'::jsonb,
    true
  ),
  (
    'Micrófonos recargables inalámbricos',
    'Universal Pro',
    'Audio profesional y micrófonos',
    'Sistemas inalámbricos',
    40,
    null,
    4.92,
    58,
    7,
    true,
    false,
    false,
    false,
    false,
    true,
    'contain',
    ARRAY['/products/microfonos-recargables-inalambricos-1.jpg']::text[],
    'Sistema doble de micrófonos inalámbricos de mano universales con minirreceptor portátil (Professional Universal Wireless Microphone).',
    '{"Tipo de cápsula":"Dinámica unidireccional con patrón polar cardioide.","Banda de frecuencia":"UHF (frecuencia ultra alta) para minimizar interferencias.","Número de canales":"2 canales independientes con frecuencias seleccionables.","Receptor":"Mini receptor portátil recargable con conector Plug 6.35 mm (1/4\") directo y antena flexible incorporada.","Pantallas en micrófonos":"Pantalla LCD en cada cuerpo que muestra el número de canal, la frecuencia activa (MHz) y el estado de carga."}'::jsonb,
    ARRAY['Sistema inalámbrico dual de 2 canales', 'Micrófonos recargables', 'Minirreceptor portátil con antena flexible', 'Pantalla LCD en cada micrófono']::text[],
    '{"type":"mic_warmth","duration":5,"notesDescription":"Micrófonos recargables inalámbricos"}'::jsonb,
    true
  ),
  (
    'Micrófonos inalámbricos Shure SN-603',
    'Shure',
    'Audio profesional y micrófonos',
    'Sistemas inalámbricos',
    65,
    null,
    4.9,
    142,
    9,
    false,
    true,
    true,
    false,
    false,
    true,
    'contain',
    ARRAY['/products/shure-sn-603-1.jpg', '/products/shure-sn-603-2.jpg']::text[],
    'Sistema de micrófonos inalámbricos dobles tipo Shure Performance Wireless (con receptor modelo SH-608).',
    '{"Tipo de micrófono":"Dinámico unidireccional con patrón polar cardioide.","Número de canales":"2 canales independientes (transmisión dual para uso simultáneo de ambos micrófonos).","Banda de frecuencia":"UHF (Ultra High Frequency), diseñada para mayor estabilidad de señal y menor interferencia ambiental.","Pantallas de visualización":"En micrófonos: Pantalla digital LCD que indica el canal activo y estado de la transmisión."}'::jsonb,
    ARRAY['Sistema inalámbrico dual de 2 canales', 'Dos micrófonos dinámicos unidireccionales', 'Transmisión UHF estable', 'Pantalla LCD en cada micrófono']::text[],
    '{"type":"mic_warmth","duration":5,"notesDescription":"Micrófonos inalámbricos Shure SN-603"}'::jsonb,
    true
  ),
  (
    'Timbales latinos 13" pulgadas',
    'Zona Audio',
    'Baterías y percusión',
    'Timbales latinos',
    350,
    null,
    4.95,
    51,
    0,
    true,
    true,
    false,
    false,
    false,
    false,
    'contain',
    ARRAY['/products/timbales-latinos-13.jpg']::text[],
    'Es un juego de timbales latinos (13") pulgadas fabricados en acero cromado, diseñados para ritmos tropicales como salsa y cumbia. Viene listo para tocar e incluye atril de doble pata regulable en altura, cencerro con soporte, baquetas y llave de afinación.',
    '{"Medidas":"Set de 13\" pulgadas.","Material":"Vaso de acero/metal cromado brillante.","Atril":"Soporte de metal reforzado de doble pata, ajustable en altura e inclinación.","Accesorios":"Incluye cencerro con su agarre, baquetas y llave de afinación.","Parches":"Sintéticos con sistema de tensores laterales de metal."}'::jsonb,
    ARRAY['Juego de timbales latinos de 13" pulgadas', 'Fabricados en acero cromado brillante', 'Incluye atril doble pata regulable en altura', 'Viene con cencerro, baquetas y llave de afinación']::text[],
    '{"type":"drums_latin","duration":5,"notesDescription":"Timbales latinos 13 pulgadas"}'::jsonb,
    true
  ),
  (
    'Micrófonos de cintillo dual',
    'U12 Series',
    'Audio profesional y micrófonos',
    'Micrófonos de cintillo',
    65,
    null,
    5,
    68,
    2,
    false,
    true,
    false,
    false,
    false,
    true,
    'contain',
    ARRAY['/products/microfonos-cintillo-dual-1.jpg']::text[],
    'Sistema doble de micrófonos de cintillo (diadema) inalámbricos UHF tipo U12 Series.',
    '{"Tecnología":"Frecuencia UHF para conexión estable y sin interferencias.","Formato":"Sistema dual con 2 micrófonos de cintillo y 2 transmisores tipo petaca.","Receptor":"Plug de 6.35 mm (1/4\") portátil con adaptador a 3.5 mm incluido.","Alimentación":"Baterías internas recargables vía cable USB doble incluido.","Uso ideal":"Clases, exposiciones, eventos y fitness (operación con manos libres para 2 personas)."}'::jsonb,
    ARRAY['Transmisión UHF estable', 'Dos transmisores tipo petaca', 'Adaptador de 3.5 mm incluido', 'Operación manos libres para 2 personas']::text[],
    '{"type":"mic_warmth","duration":5,"notesDescription":"Micrófonos de cintillo dual U12 Series"}'::jsonb,
    true
  ),
  (
    'Paral profesional para micrófono',
    'Professional Stand',
    'Accesorios',
    'Soportes para micrófono',
    20,
    null,
    4.96,
    33,
    3,
    false,
    false,
    false,
    false,
    false,
    true,
    'contain',
    ARRAY['/products/paral-profesional-microfono-2.jpg']::text[],
    'Paral profesional para micrófono de pedestal con brazo jirafa (boom) y doble clip (Professional Microphone Stand).',
    '{"Estructura tipo jirafa (Boom)":"Brazo extensible y ajustable en ángulo para mayor alcance y flexibilidad de posición.","Doble capacidad":"Incluye 2 clips/pinzas para sujetar dos micrófonos al mismo tiempo (uno en el brazo y otro en el eje central).","Base de trípode plegable":"Patas de tres apoyos con gomas antideslizantes que brindan excelente estabilidad y facilidad de transporte.","Altura regulable":"Ajuste telescópico de altura mediante perillas metálicas/plásticas de rosca.","Diseño y material":"Construcción liviana en metal negro de alta resistencia, apto para escenarios, ensayos y grabación."}'::jsonb,
    ARRAY['Brazo boom extensible y ajustable', 'Dos pinzas para dos micrófonos', 'Base de trípode plegable', 'Altura telescópica regulable']::text[],
    '{"type":"synth_lead","duration":5,"notesDescription":"Paral profesional para micrófono"}'::jsonb,
    true
  ),
  (
    'Paral para micrófono de escritorio',
    'Professional Stand',
    'Accesorios',
    'Soportes para micrófono',
    16,
    null,
    4.99,
    420,
    35,
    false,
    false,
    true,
    false,
    false,
    true,
    'contain',
    ARRAY['/products/paral-microfono-escritorio-1.jpg']::text[],
    'Es un soporte compacto de escritorio diseñado para mantener un micrófono estable sobre mesas o podios. Su diseño firme de base ponderada ocupa muy poco espacio, haciéndolo ideal para podcasts, conferencias, transmisiones en vivo, grabaciones de voz y reuniones virtuales.',
    '{"Base redonda pesada":"Proporciona estabilidad sólida en superficies planas para evitar volcamientos.","Altura ajustable":"Tubo central telescópico con rosca de fijación para graduar la altura del micrófono fácilmente.","Sujetador incluido":"Viene con pinza/clip universal para micrófonos de mano.","Inclinación regulable":"Permite ajustar el ángulo del micrófono según la posición del usuario.","Diseño compacto":"Ligero, fácil de armar y transportar."}'::jsonb,
    ARRAY['Base redonda pesada y estable', 'Altura telescópica ajustable', 'Pinza universal incluida', 'Inclinación regulable']::text[],
    '{"type":"mic_warmth","duration":5,"notesDescription":"Paral para micrófono de escritorio"}'::jsonb,
    true
  );
